import Head from "next/head";
import NavBar from "../components/core/NavBar";
import Features from "../components/core/Features";
import Testimonial from "../components/core/Testimonial";
import Footer from "../components/core/Footer";
import Hero from "../components/core/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>TeenVest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="../static/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <Hero />
        <Features />
        <Testimonial />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
