import Head from "next/head";
import LandingPage from "../components/core/LandingPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>TeenVest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LandingPage />
      </main>
    </div>
  );
}
